### ISSUE TITLE
Java programs cannot be parsed if they have two equally named local variables

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#120] opened 2022-12-23 23:29 UTC
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/120) where the discussions are preserved.
    
----
    
* Mantis: [MT-1532](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1532)
* Submitted on: 2015-02-26 by (at)mulbrich
* Updated: 2015-04-29

### Description

> If two equally named local variables are declared within one method like in
> 
>    for(int i = ...) {}
>    for(int i = ...) {}
> 
> KeY cannot parse the file if there are loop invariants annotations. W/o
> them, parsing works. I assume a problem within the JML parser, hence.
> 
> (Having two variables with the same in separate parts of the method is
> legal in Java and also common practice)

### Steps to reproduce

```
Try to load the attached file - it will fail with an exception:

(class java.lang.RuntimeException)
java.lang.RuntimeException: Name already in namespace: i
	at de.uka.ilkd.key.logic.Namespace.addSafely(Namespace.java:130)
	at de.uka.ilkd.key.speclang.translation.SLResolverManager.putIntoTopLocalVariablesNamespace(SLResolverManager.java:250)
	at de.uka.ilkd.key.speclang.translation.SLResolverManager.putIntoTopLocalVariablesNamespace(SLResolverManager.java:279)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.<init>(KeYJMLParser.java:118)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.<init>(KeYJMLParser.java:135)
	at de.uka.ilkd.key.speclang.jml.translation.JMLTranslator.translate(JMLTranslator.java:1735)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.createJMLLoopInvariant(JMLSpecFactory.java:1436)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.createJMLLoopInvariant(JMLSpecFactory.java:1536)
	at de.uka.ilkd.key.speclang.jml.JMLSpecExtractor.extractLoopInvariant(JMLSpecExtractor.java:639)
	at de.uka.ilkd.key.speclang.SLEnvInput.createSpecs(SLEnvInput.java:301)
	at de.uka.ilkd.key.speclang.SLEnvInput.read(SLEnvInput.java:370)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.readEnvInput(ProblemInitializer.java:360)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:535)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:491)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.createInitConfig(AbstractProblemLoader.java:411)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.load(AbstractProblemLoader.java:222)
	at de.uka.ilkd.key.proof.io.ProblemLoader.doWork(ProblemLoader.java:72)
	at de.uka.ilkd.key.proof.io.ProblemLoader.access$000(ProblemLoader.java:36)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:118)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:111)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concu(class java.lang.RuntimeException)
java.lang.RuntimeException: Name already in namespace: i
	at de.uka.ilkd.key.logic.Namespace.addSafely(Namespace.java:130)
	at de.uka.ilkd.key.speclang.translation.SLResolverManager.putIntoTopLocalVariablesNamespace(SLResolverManager.java:250)
	at de.uka.ilkd.key.speclang.translation.SLResolverManager.putIntoTopLocalVariablesNamespace(SLResolverManager.java:279)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.<init>(KeYJMLParser.java:118)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.<init>(KeYJMLParser.java:135)
	at de.uka.ilkd.key.speclang.jml.translation.JMLTranslator.translate(JMLTranslator.java:1735)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.createJMLLoopInvariant(JMLSpecFactory.java:1436)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.createJMLLoopInvariant(JMLSpecFactory.java:1536)
	at de.uka.ilkd.key.speclang.jml.JMLSpecExtractor.extractLoopInvariant(JMLSpecExtractor.java:639)
	at de.uka.ilkd.key.speclang.SLEnvInput.createSpecs(SLEnvInput.java:301)
	at de.uka.ilkd.key.speclang.SLEnvInput.read(SLEnvInput.java:370)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.readEnvInput(ProblemInitializer.java:360)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:535)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:491)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.createInitConfig(AbstractProblemLoader.java:411)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.load(AbstractProblemLoader.java:222)
	at de.uka.ilkd.key.proof.io.ProblemLoader.doWork(ProblemLoader.java:72)
	at de.uka.ilkd.key.proof.io.ProblemLoader.access$000(ProblemLoader.java:36)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:118)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:111)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
rrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

## Associated Bugs

* Relates to MT-1409 with 

* Relates to MT-1416 with 

## History

* (at)mulbrich -- (`NEW_BUG`) _2015-02-26_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2015-04-29_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2015-04-29_

## Attributes

* Category: JML Parser
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: ecc7bdbafff8cc3d4fdb5697ad91c0f94fe7bc2d
* Build: 
* Tags []
* Labels:  ~JML Parser  ~Bug  ~NORMAL  
* Version: _2.4_ 

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1532)
    
----
    
Information: 
* created_at: 2017-05-29T02:29:44.954Z
* updated_at: 2021-12-11T15:27:02.670Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment] 2023-08-31 07:32
Duplicate of #1212

**Closed by FliegendeWurst** 2023-08-31 07:32 UTC
Labels: JML Parser, :lady_beetle: Bug, P:NORMAL
