### ISSUE TITLE
KeY silently removes parts of unsupported \sum expressions to make \bsum's

### ISSUE THREAD

**Issue by Mikescher** [KeYProject/key#3035] opened 2023-02-14 18:46 UTC
## Description

KeY only supports \sum expressions of the form `\sum T x; n <= x && x < m; t` and converts them to bsum terms. (see KeY book chap 8.1.2.3)

When writing a specification with a \sum expression that is not supported by KeY (because it has 3 conditions) the additional parts of the sum-condition get silently removed to make it a valid (but different) bsum expression. 

For example `( \sum int x; 0 <= x && x < values.length && values[x]>=0; values[x]) ` gets treated the same as `( \sum int x; 0 <= x && x < values.length; values[x] )`

## Reproducible
  
always

### Steps to reproduce 

1. Load this example program:
```java
class Example20230214 {
    int[] values;

    /*@ normal_behaviour
      @
      @ requires true;
      @
      @ ensures ( \sum int x; 0 <= x && x < values.length;           values[x] ) == 
      @         ( \sum int x; 0 <= x && x < values.length && x%2==0; values[x] );
      @
      @ assignable \nothing;
      @*/
    void sumExample() {  }
}
```

2. Observe that both \sum expressions get translated to the same term on the sequent:  `javaCastInt(bsum{int x;}(0, self.values.length, self.values[x]))`

3.  The AutoPilot closes the proof (but imo shouldn't)

### Expected behaviour

Generate a raw `sum` term (similar to \sum expressions that are totally different from the bsum form) - or throw an error.

### Additional information

Reproduced on the current ~~master~~ main branch ( 87ceb1cd6f965beeb584b66d372ee5eb09cf4571 )

**Comment by mattulbrich** [comment] 2023-03-08 15:20
This is a duplicate of #1675.

**Closed** 2023-03-09 11:28 UTC
Labels: good first issue, JML Parser, :lady_beetle: Bug, P:HIGH, ✋ Soundness
