### ISSUE TITLE
Proof files with manual formula input cannot be loaded

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1561] opened 2022-12-23 23:39 UTC
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1561) where the discussions are preserved.
    
----
    
## Description

If rules are applied interactively with user input, they may not be reloadable after saving.

The problem is that symbols are named differently when loading.
In particular, the `self` variable usually has a name similar to `self_25`. That is fine within a single proof, but becomes problematic when reloading. When reloading, the variable is called `self`. If a (little sensible) cut `self_25=null` had been made, it would not be reloadable: in the new environment `self_25` isn't a valid name.

## Reproducible
  
always

### Steps to reproduce 

Try to load the attached proof bundle: [problem.zproof](/uploads/666241a28f3785d446f9dd3d32ff2c98/problem.zproof)

### Additional information

The culprit seems to be in [AbstractOperationPO:622](https://git.key-project.org/key/key/-/blob/a3cd916f85e4a52092723a6bb05c97d98b531763/key/key.core/src/main/java/de/uka/ilkd/key/proof/init/AbstractOperationPO.java#L622). For some reason, the proof obligations are deliberately created with disctinct names.

It is not clear to the bug reporter, why this must ever return true.

A potential bug fix would be to change this to `return false`. But ... what would that break?

From the commit history, I'd surmise that it has to do with the symbex engine. 

---

* Commit: a3cd916f85e4a52092723a6bb05c97d98b531763 (master at the time)

    
----
    
Information: 
* created_at: 2021-02-23T17:15:51.076Z
* updated_at: 2021-02-25T14:48:32.578Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 2

**Comment by FliegendeWurst** [comment] 2023-08-02 07:18
Duplicate of #1552

**Closed by FliegendeWurst** 2023-08-02 07:18 UTC
Labels: :lady_beetle: Bug, P:NORMAL, Symb. Debugger, Proof Loading/Saving
